const SET_ISLOADING = "SET_ISLOADING";
const CLEAR_ISLOADING = "CLEAR_ISLOADING";
const SET_CARDS = "SET_CARDS";
const SET_CURRENTCARD = "SET_CURRENTCARD";
const SET_POPUPMESSAGE = "SET_POPUPMESSAGE";
const CLEAR_POPUPMESSAGE = "CLEAR_POPUPMESSAGE";

export {
  SET_ISLOADING,
  CLEAR_ISLOADING,
  SET_CARDS,
  SET_CURRENTCARD,
  SET_POPUPMESSAGE,
  CLEAR_POPUPMESSAGE,
};
